### ISSUE TITLE
Synchronization Bug in Distributed Environments

### ISSUE THREAD

**Issue by chadlzx** [lucidrains/vector-quantize-pytorch#101]
I found a critical bug in the master branch, file `vector_quantize_pytorch.py`, at line 496 and 667. The code in question is:
`
self.all_reduce_fn(embed_sum.contiguous())
`
In the distributed environment, this code fails to properly synchronize embed_sum. The issue arises because this operation might create a new tensor, which leads to synchronization problems.

**Comment by lucidrains** [comment]
@chadlzx hmm that's odd, i'm relying on [pytorch collectives](https://pytorch.org/docs/stable/distributed.html)

**Comment by lucidrains** [comment]
@chadlzx 🤦 omg, yea i see what happened

thank you Liu! should be corrected in the latest version

**Comment by chenjiasheng** [comment]
the reason why this happens:
`embed_sum.contiguous()` is a temporary variable, i.e., a right value.
while the arg to `all_reduce()` has to be a left referencable variable, since it is an in/out argument.
