### ISSUE TITLE
About requirements

### ISSUE THREAD

**Issue by takenori-y** [lucidrains/vector-quantize-pytorch#104]
The newly released version uses the einx package. This package seems to require PyTorch >= 2.1.
https://pytorch.org/docs/2.1/torch.compiler.html#torch-compiler
 
Just a question: do you intend to drop support for PyTorch <= 2.0 in the new release?

**Comment by lucidrains** [comment]
@takenori-y hey Takenori, yes I think it is worth enforcing the strict requirements for `get_at`
