### ISSUE TITLE
nan encountered in `cdist()`

### ISSUE THREAD

**Issue by chenjiasheng** [lucidrains/vector-quantize-pytorch#106]
https://github.com/lucidrains/vector-quantize-pytorch/blob/115558857db741b95029857275a8129971b3e407/vector_quantize_pytorch/vector_quantize_pytorch.py#L33

`(x-y)^2` could be negative if computed as `x^2 + y^2 - 2xy` due to float precision overflow.
so the resulted dist may contain some `nan`.
`torch.clamp(..., min=0)` is required here.

**Comment by chenjiasheng** [comment]
@lucidrains

**Comment by lucidrains** [comment]
@chenjiasheng ah nice catch!

let me know if 1.14.1 resolves it

**Comment by Boltzmachine** [comment]
looks like 0 is not sufficient for me. Probably we need 1e-7 or something alike.

**Comment by lucidrains** [comment]
@Boltzmachine that's strange, you are seeing NaNs still?

**Comment by Boltzmachine** [comment]
the derivative of `sqrt(x)`, i.e., `1/(2sqrt(x))`

**Comment by lucidrains** [comment]
@Boltzmachine ohh you are differentiating through the distance? yeah I've forgotten about that

**Comment by Boltzmachine** [comment]
wait don't we always differentiate through the distance when training the model?

**Comment by Boltzmachine** [comment]
I am trying to confirm the originates of the NaNs. Btw does the rotation tirck avoid such issues?

**Comment by lucidrains** [comment]
@Boltzmachine yea I defaulted it to True due to how extraordinary it was as a technique 

Ill add a setting to clamp it to a eps later, as I believe I also have some old features that differentiate through it

thanks for reraising this issue!
