### ISSUE TITLE
Modernizing the setup 

### ISSUE THREAD

**Issue by MisterBourbaki** [lucidrains/vector-quantize-pytorch#119]
It would be great to upgrade the setup.py file, as it is quite old-fashioned :) As it is indicated [here](https://packaging.python.org/en/latest/guides/modernize-setup-py-project/#modernize-setup-py-project) for instance.

I could open a dedicated PR if you'd like @lucidrains !

**Comment by lucidrains** [comment]
@MisterBourbaki hey, thanks for the suggestion

could you let me know if the latest commit looks ok?

**Comment by MisterBourbaki** [comment]
That is a start :) I think you could put all that is in setup.py into pyproject.toml, in a single file.

I would also recommend the use of Poetry as a tool, but that is certainly another story.

**Comment by lucidrains** [comment]
@MisterBourbaki sounds good, i can slowly move towards the pyproject.toml way

as for poetry, i think the jury is still out. i'm personally watching [rye](https://github.com/astral-sh/rye) (have tried it on a few personal projects with success)
