### ISSUE TITLE
orthogonal regularization loss useless?

### ISSUE THREAD

**Issue by GallagherCommaJack** [lucidrains/vector-quantize-pytorch#12]
because the codebooks are not registered as trainable parameters, and the orthogonal loss is only a function of the codebooks, is the orthogonal loss entirely useless?

**Comment by lucidrains** [comment]
@GallagherCommaJack Hey Jack, thank you for catching this! Can you let me know if https://github.com/lucidrains/vector-quantize-pytorch/commit/ebce893fff695845f7fe0f04d1400d2c29b94f98 works?
