### ISSUE TITLE
Expire codes heuristic is replacing inputs

### ISSUE THREAD

**Issue by kashif** [lucidrains/vector-quantize-pytorch#13]
Thanks for the implementation! 

One question, should this 

https://github.com/lucidrains/vector-quantize-pytorch/blob/ebce893fff695845f7fe0f04d1400d2c29b94f98/vector_quantize_pytorch/vector_quantize_pytorch.py#L177

be actually `self.expire_codes_(quantize)`?

**Comment by lucidrains** [comment]
@kashif Hi Kashif, I don't believe so, because I think the logic is to replace some of the dead codes with randomly chosen vectors from the current batch

**Comment by kashif** [comment]
Hmm I see thanks
