### ISSUE TITLE
question about lfq distributed training

### ISSUE THREAD

**Issue by syyxsxx** [lucidrains/vector-quantize-pytorch#148]
hi,
Is it necessary to manually perform all_reduce on the prob during distributed training when using lfq?
https://github.com/lucidrains/vector-quantize-pytorch/blob/4c514db53457883348d8422ae01af293d78fb57f/vector_quantize_pytorch/lookup_free_quantization.py#L364
@lucidrains 
thanks advance

**Comment by lucidrains** [comment]
the very next line should take care of it
