### ISSUE TITLE
LFQ quantizer quickly converged which leads to codebook lower utilization

### ISSUE THREAD

**Issue by Jason3900** [lucidrains/vector-quantize-pytorch#154]
Hey, thanks for your excellent work.
I encountered a strange problem when using LFQ to train a video tokenizer (decoder is a magvit-v2 like structure). The reconstruction loss has difficulties to converge because LFQ's entropy loss goes up and then keeps in a steady state. In that case, the codebook utilization drops to an extremely low range. How to explain this and fix it? Appreciate for your help.

![image](https://github.com/user-attachments/assets/1134214d-51ff-42c3-9513-eeb4ef66e785)
![image](https://github.com/user-attachments/assets/cecbb6a3-52f1-49a4-9f49-120cc9c41285)
The code book unique ratio stands for the percentage of how many unique tokens in the quantized sequence.
BTW, I followed the magvit-v2 paper to use a entropy decay step and the training is conducted on ucf-101 (13k videos)

**Comment by leolin65** [comment]
how about https://github.com/zhaoyue-zephyrus/bsq-vit/blob/main/transcoder/models/quantizer/bsq.py

**Comment by Jason3900** [comment]
thanks, I've seen this before, but in practice, it seems to add two norms
before and after lfq, and scale the range of the represention. How does
these ops alliviate what I encounter?

Leonardo Lin ***@***.***> 于 2024年8月25日周日 21:42写道：

**Comment by Jason3900** [comment]
#158
