### ISSUE TITLE
There is a future warning

### ISSUE THREAD

**Issue by CyunNaam** [lucidrains/vector-quantize-pytorch#155]
anaconda3\envs\pytorch39\lib\site-packages\vector_quantize_pytorch\vector_quantize_pytorch.py:461: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.

**Comment by hide-on-bush-lalala** [comment]
碰到了一样的情况，肯呢个需要作者替换掉这个API，出现了大量的amp的FutureWarning。

**Comment by hide-on-bush-lalala** [comment]
我也可以尝试去修改这部分代码，但是对于github合作以及PR的模式不是很懂，有没有什么入门的演示。。。

**Comment by CyunNaam** [comment]
> 我也可以尝试去修改这部分代码，但是对于github合作以及PR的模式不是很懂，有没有什么入门的演示。。。

如果作者不更新的话，只能先忽略警告了
