### ISSUE TITLE
[BUG] LFQ with DDP fails

### ISSUE THREAD

**Issue by hummat** [lucidrains/vector-quantize-pytorch#159]
Using [LFQ with DDP](https://github.com/lucidrains/vector-quantize-pytorch/blob/59304110b656e2865e15e5918a2c9e82989decb8/vector_quantize_pytorch/lookup_free_quantization.py#L39) fails with `AttributeError: module 'torch.distributed' has no attribute 'nn'`. Using `from torch.distributed import nn as dist_nn` seems to work, which is strange.

**Comment by lucidrains** [comment]
@hummat oops, fixed!
