### ISSUE TITLE
Implementation of Regularized Vector Quantization

### ISSUE THREAD

**Issue by UkiTenzai** [lucidrains/vector-quantize-pytorch#161]
Hello, I have read a paper _Regularized Vector Quantization for Tokenized Image Synthesis_ , which is available at https://arxiv.org/abs/2303.06424  .  It presents a regularized vector quantization framework that significantly increase codebook usage. Will it be implemented in this project in the future?
Thank you very much for your contribution.

**Comment by lucidrains** [comment]
@UkiTenzai yea it looks interesting, esp the visualization of the codebooks

any ideas why the PSNR seems to suffer?

**Comment by UkiTenzai** [comment]
I have no other ideas than the expansion of the discrete features distributions. So I wanted to reproduce it and explore the relationship between codebook utilization and reconstruction quality.
Anyway, It is true that many vectors are wasted in the traditional codebook.

**Comment by UkiTenzai** [comment]
I have no other ideas than the expansion of the discrete features distributions. So I wanted to reproduce it and explore the relationship between codebook utilization and reconstruction quality.
Anyway, It is true that many vectors are wasted in the traditional codebook.

**Comment by lucidrains** [comment]
@UkiTenzai hey, so i think they involve a trained VGG for the contrastive learning portion?

**Comment by lucidrains** [comment]
@UkiTenzai there's a few smells to the paper, so i'm going to pass

i already have some of the stochastic settings the paper mentioned in the repo, just not the extra regularizations
