### ISSUE TITLE
Check if we actually training

### ISSUE THREAD

**Issue by inspirit** [lucidrains/vector-quantize-pytorch#163]
Hi Phil,

I believe we need to make sure we are training RVQ before updating codebooks:
https://github.com/lucidrains/vector-quantize-pytorch/blob/22a03755f3acc1e011ecf37706496eb249f68f90/vector_quantize_pytorch/residual_vq.py#L370

**Comment by lucidrains** [comment]
@inspirit ah yes indeed, thanks!
