### ISSUE TITLE
[suggestion] default value of `commitment_loss_weight` in `LFQ`

### ISSUE THREAD

**Issue by danelee2601** [lucidrains/vector-quantize-pytorch#165]
I've been using LFQ for a while, and noticed that `commitment_loss_weight` in LFQ is set to 0.25. But I think it can be simply zero because there is no concern of embedding divergence unlike VQ where the purpose of the commitment loss is to prevent the divergence.

I experimentally found that setting `commitment_loss_weight` to zero leads to better training convergence. But note that I didn't do thorough experiment and experimented in the MaskBit setup.

**Comment by lucidrains** [comment]
@danelee2601 hey, thank you for sharing this! yes lets roll with that
