### ISSUE TITLE
codebook update

### ISSUE THREAD

**Issue by dorsa-zeinali** [lucidrains/vector-quantize-pytorch#167]
Hi, 
I had a question about the VectorQuantize function. Is the codebook updated even when I am not strictly training any of its parameters? 

Thank you!

**Comment by lucidrains** [comment]
@dorsa-zeinali if you are using ema updates (which you should) then yes

**Comment by dorsa-zeinali** [comment]
thank you for replying! should the threshold_ema_dead_code be higher for better performance?

**Comment by lucidrains** [comment]
@dorsa-zeinali you may not even need that anymore given the recent "rotation trick" from Fifty et al.

**Comment by dorsa-zeinali** [comment]
Sorry for so many questions and thanks for answering, but which one of these algorithms are more uniform (produce a more uniform codebook?)

**Comment by lucidrains** [comment]
best way to answer that question is to run your own experiments in the examples folder and trust your own eyes

**Comment by lucidrains** [comment]
@MHVali yup, that's right, you need to use the EMA!

**Comment by MHVali** [comment]
Thanks a lot for your prompt response!
I'm using the rotation trick for an image compression task using VQ-VAE. But, I got much worse results than STE when using rotation technique by optimizing the codebook via EMA with decay rate=0.8 (value from the paper). But, I'm getting really nice results when using EMA with STE to backprop the grads from VQ using decay rate=0.99.
So, I have a question regarding the inputs to the **rotate_to(src, tgt)** function. I think **src** is the flattened encoder's output (e) and **tgt** is the flattened hard quantized version of e that is the non-differentiable. Just wanted to make sure both src and tgt are flattened with the shape of "BHW x C". Right?
