### ISSUE TITLE
version 1.19.1 randint() received an invalid combination of arguments - got (int, torch.device, tuple)

### ISSUE THREAD

**Issue by yangperasd** [lucidrains/vector-quantize-pytorch#171]
version 1.19.1
in residual_fsq.py
![image](https://github.com/user-attachments/assets/aa64c572-0be7-4472-945a-996ff65615c7)
![image](https://github.com/user-attachments/assets/f94cfcf7-8067-4f59-a181-a397fbdf8714)
![image](https://github.com/user-attachments/assets/7b7079b1-80ca-4e72-a5b3-0c99dcf75aed)
randint api
![image](https://github.com/user-attachments/assets/327ae52c-4fa5-4bc1-954d-3657edd2e29b)

i fix this by
![image](https://github.com/user-attachments/assets/ba11f344-3bdd-4de3-aed6-347673d66559)
![image](https://github.com/user-attachments/assets/38127c6a-0e9e-417d-839e-c353363152aa)
![image](https://github.com/user-attachments/assets/7e1512fb-0c80-4092-a281-a776ae59d1ee)

or should i make a PR?

**Comment by lucidrains** [comment]
@yangperasd thanks! wow, there's a lot of people using this experimental feature

**Comment by lucidrains** [comment]
i should intentionally break things from time to time just to figure out if researchers are quietly using something i improvised
