### ISSUE TITLE
Vit-VQGAN

### ISSUE THREAD

**Issue by snarb** [lucidrains/vector-quantize-pytorch#21]
Hello. Thanks for great repo. Is [Vit-VQGAN](https://arxiv.org/abs/2110.04627) is implemented in this repo? Looks like it is far away from cnn decoders/encoders in performance/ quality

**Comment by lucidrains** [comment]
@snarb Hello Pavel! I have it implemented at https://github.com/lucidrains/parti-pytorch/blob/main/parti_pytorch/vit_vqgan.py
