### ISSUE TITLE
kmeans and ddp hangs

### ISSUE THREAD

**Issue by tasptz** [lucidrains/vector-quantize-pytorch#25]
kmeans and ddp hangs for me. ddp is initialized by pytorch lightning in my case. I have several questions:

In https://github.com/lucidrains/vector-quantize-pytorch/blob/master/vector_quantize_pytorch/vector_quantize_pytorch.py#L98

`all_num_samples = all_gather_sizes(local_samples, dim = 0)` should it be `dim = 1` (as dim 0 is the codebook dimension)?

Then in https://github.com/lucidrains/vector-quantize-pytorch/blob/master/vector_quantize_pytorch/vector_quantize_pytorch.py#L93 it just hangs for me. I am not totally sure, but I believe `distributed.broadcast` in

https://github.com/lucidrains/vector-quantize-pytorch/blob/master/vector_quantize_pytorch/vector_quantize_pytorch.py#L90

is called with incompatible shapes. See https://pytorch.org/docs/stable/distributed.html#torch.distributed.broadcast

> tensor must have the same number of elements in all processes participating in the collective.

**Comment by lucidrains** [comment]
@tasptz oh crap, yea i can try to fix this

i must have broken it moving it to multiple codebooks for multi-headed vq

**Comment by lucidrains** [comment]
https://github.com/lucidrains/vector-quantize-pytorch/commit/ccfaac6638b908d49b69cfaae924f30b80e9c3a9

@tasptz could you see if the latest changes resolve your issue? if not, you can also turn it off by setting `sync_kmeans = False`

@falkaer also pinging Kenny, as he PR-ed in most of this code https://github.com/lucidrains/vector-quantize-pytorch/pull/17

**Comment by lucidrains** [comment]
i'll try to get this resolved by week's end

**Comment by lucidrains** [comment]
@tasptz Hi Thomas, I think it should be fixed in `0.10.2`, please reopen the issue if otherwise!

https://github.com/lucidrains/vector-quantize-pytorch/commit/e7ced714b7aa0bd5598d1547d26a8570c5b004a3
