### ISSUE TITLE
L2 norm in the replace codes for EuclideanCodebook seems unnecessary

### ISSUE THREAD

**Issue by apoorv2904** [lucidrains/vector-quantize-pytorch#36]
Hi,

The batch samples are l2normalized when replacing the codes for the EuclideanCodebook. This doesn't seem correct for the Euclidean case.

https://github.com/lucidrains/vector-quantize-pytorch/blob/master/vector_quantize_pytorch/vector_quantize_pytorch.py#L245

Thanks,
Apoorv

**Comment by lucidrains** [comment]
@apoorv2904 oh gosh, yes! thank you Apoorv!
