### ISSUE TITLE
It seems that the vector from the GPU cannot be input

### ISSUE THREAD

**Issue by fyqqyf** [lucidrains/vector-quantize-pytorch#37]
```
import torch
from vector_quantize_pytorch import VectorQuantize

vq = VectorQuantize(
    dim = 256,
    codebook_size = 512,     # codebook size
    decay = 0.8,             # the exponential moving average decay, lower means the dictionary will change faster
    commitment_weight = 1.   # the weight on the commitment loss
)

x = torch.randn(1, 1024, 256)
x = x.cuda()
quantized, indices, commit_loss = vq(x) # (1, 1024, 256), (1, 1024), (1)
```

> File "/vector_quantize_pytorch/vector_quantize_pytorch.py", line 280, in forward
>     dist = -torch.cdist(flatten, embed, p = 2)
>   File "/torch/functional.py", line 1153, in cdist
>     return _VF.cdist(x1, x2, p, None)  # type: ignore[attr-defined]
> RuntimeError: X1 and X2 must have the same device type. X1: cuda X2: cpu
How to change it to adapt to GPU?
Thanks!

**Comment by lucidrains** [comment]
@fyqqyf you need to place the vq instance on cuda as well `vq = vq.cuda()`
