### ISSUE TITLE
How to get the quantized_out from the all_indices

### ISSUE THREAD

**Issue by Autonomf** [lucidrains/vector-quantize-pytorch#44]
I want to get the quantized_out from the all_indices,but I do not konw how I can do.

https://github.com/lucidrains/vector-quantize-pytorch/blob/5838df707a900134c4fc36ba2cae9e817959e8b8/vector_quantize_pytorch/residual_vq.py#L176

**Comment by lucidrains** [comment]
@Autonomf you would simply use `get_codes_from_indices`

```python
import torch
from vector_quantize_pytorch import ResidualVQ

residual_vq = ResidualVQ(
    dim = 256,
    codebook_size = 256,
    num_quantizers = 2,
    kmeans_init = True,
    kmeans_iters = 10
)

x = torch.randn(1, 1024, 256)

residual_vq.eval()

quantized, indices, commit_loss = residual_vq(x)

quantized_out = residual_vq.get_codes_from_indices(indices)  # pass your indices into here, but the indices must come during .eval(), as during training some of the indices are dropped out (-1)

assert torch.all(quantized == quantized_out.sum(dim = 0))

```

**Comment by Autonomf** [comment]
OK，very thanks！！！
I just did not use the funcition get_codes_from_indices during .eval(), so do not get the result always.

**Comment by lucidrains** [comment]
@Autonomf no problem, good luck with your project
