### ISSUE TITLE
[Feature Request] Support Multi-Head Residual VQ

### ISSUE THREAD

**Issue by BakerBunker** [lucidrains/vector-quantize-pytorch#46]
Recent [HiFi-codec paper](https://arxiv.org/pdf/2305.02765.pdf) proposed a "Group-Residual Vector Quantization" method.
![2023-05-06 15 35 58](https://user-images.githubusercontent.com/17872844/236610207-134ac3a6-f52a-4caf-9023-52f4b764716b.png)

**Comment by lucidrains** [comment]
very cool! yea i can definitely support this!

**Comment by lucidrains** [comment]
ok, it is done https://github.com/lucidrains/vector-quantize-pytorch/commit/bf531373122321bbe47ab1a7693351a2c1cb416e#diff-ef951f5680b9f7fcf9742bba0c4407b9f5c787d1e489b8cc31773245bc42bf3fR193
