### ISSUE TITLE
Bug with distributed training and Cosine codebook

### ISSUE THREAD

**Issue by pdura-sanas** [lucidrains/vector-quantize-pytorch#51]
Error:
> RuntimeError: Tensors must be contiguous

Fix:
> self.all_reduce_fn(embed_sum.contiguous())
at:
https://github.com/lucidrains/vector-quantize-pytorch/blob/f162fc356f5f38334a94f1d8f468aa28c7c46700/vector_quantize_pytorch/vector_quantize_pytorch.py#L595

**Comment by lucidrains** [comment]
@pdura-sanas thank you! :pray:
