### ISSUE TITLE
Gradient of gumbel straight through multiplier was not correct.

### ISSUE THREAD

**Issue by Zyriix** [lucidrains/vector-quantize-pytorch#59]
In function gumbel_sample(vector_quantize_pytorch.py line 92).
`  st_mult = one_hot.gather(-1, rearrange(ind, '... -> ... 1')) # multiplier for straight-through`
we gather the one hot to get the st_mult. and the mult it with gathered embedding.
Just like this:
`
onehot = gather(onehot)
emb = gather(emb)
emb = emb*onehot
`

But I found this is different in taming transformer codebase
`
emb = torch.einsum('bs,sd->b,s',onehot,emb)
`

It seems it is the same since the output of first code and second code was the same.

But**The gradient of first code was not correct**.
This is because even the most value of onehot is zero. Those zero will get gradient.
Just like ControlNet's zero conv if you are interested about it.

let's consider this:
x = [x1,x2]
y = [1,0]
o = x1*1+x2*0

the gradient to y2 = D o/D x2. and this is not zero!
Test on my own code:
![image](https://github.com/lucidrains/vector-quantize-pytorch/assets/40727904/cf103488-07e3-4822-9a16-2b96d54da87b)
![image](https://github.com/lucidrains/vector-quantize-pytorch/assets/40727904/203c55c5-79fe-4030-a720-6e6933323a7e)

Please let me know if i made any mistake, thanks again for your contributions.

**Comment by lucidrains** [comment]
@Zyriix hey, thanks for the review, i think you are correct and [made the change](https://github.com/lucidrains/vector-quantize-pytorch/issues/59)

**Comment by lucidrains** [comment]
@Zyriix i need to read the controlnet paper still for this zero conv trick! i heard controlnet has really taken off in usage

**Comment by Zyriix** [comment]
Thanks for your prompt reply. Hope this repo can help more people. Close this as it was finished.
