### ISSUE TITLE
Training when input to be be quantized contains padding

### ISSUE THREAD

**Issue by sohananisetty** [lucidrains/vector-quantize-pytorch#62]
When we perform quantization of a batch of sequences, with each sequence padded to the longest length in the batch, I would assume that while calculating and ordering the Euclidean distances for each embedding in a sequence, we would have to ignore the embeddings corresponding to the pad indices during training/updating the codebook.  This is not explicitly defined in the code. Can this have a negative effect or is it safe to ignore?

**Comment by sohananisetty** [comment]
Thanks! The codebase is definitely getting pretty complex compared to what I remember 6 months ago:). I guess that's the downside of researchers doing weird things and limit testing stuff.

**Comment by lucidrains** [comment]
haha yes indeed

i'll try to remove feature moving forward, depending on what researchers tell me what works or not

**Comment by lucidrains** [comment]
for now, because residual VQ is such a big success in the audio domain, we will have to stick with the complexity
