### ISSUE TITLE
Decode function

### ISSUE THREAD

**Issue by brjathu** [lucidrains/vector-quantize-pytorch#65]
Hi,

Thanks for writing a great code base!
I have a use case, where I have a set of indices predicted from a different network, now I want to reconstruct an image from this set of indices, could you please provide a `decode()` function which converts indices to quantized vectors?

Thanks

**Comment by sonipriyanka1990** [comment]
Hi, you can refer to this function: get_codes_from_indices. It is also discussed here: https://github.com/lucidrains/vector-quantize-pytorch/issues/44

**Comment by brjathu** [comment]
Hi, thanks for your response, yes this function only returns the codes for the codebook, but for reconstruction purpose I need the final decoded vectors. For example, if we use a lower dimensional codebook, above code will fail. 

```python
import torch
from vector_quantize_pytorch import ResidualVQ

residual_vq = ResidualVQ(
    dim = 256,
    codebook_size = 256,
    num_quantizers = 2,
    kmeans_init = True,
    kmeans_iters = 10,
    codebook_dim = 16,
)

x = torch.randn(1, 1024, 256)

residual_vq.eval()

quantized, indices, commit_loss = residual_vq(x)

quantized_out = residual_vq.get_codes_from_indices(indices)  # pass your indices into here, but the indices must come during .eval(), as during training some of the indices are dropped out (-1)

assert torch.all(quantized == quantized_out.sum(dim = 0))
```

**Comment by lucidrains** [comment]
@brjathu thanks for raising this issue, as it made me realize that when model and codebook dimensions differ, the residual vq has redundant linear projections

this should be the correct logic in the presence of projections

```python
import torch
from vector_quantize_pytorch import ResidualVQ

residual_vq = ResidualVQ(
    dim = 256,
    codebook_size = 256,
    num_quantizers = 2,
    kmeans_init = True,
    kmeans_iters = 10,
    codebook_dim = 16,
)

x = torch.randn(1, 1024, 256)

residual_vq.eval()

quantized, indices, commit_loss = residual_vq(x)

quantized_out = residual_vq.get_codes_from_indices(indices)  # pass your indices into here, but the indices must come during .eval(), as during training some of the indices are dropped out (-1)
quantized_out = residual_vq.project_out(quantized_out.sum(dim = 0))

assert torch.all(quantized == quantized_out)
```

**Comment by brjathu** [comment]
Awesome!, thank you so much for fixing this issue. It works perfectly!
