### ISSUE TITLE
K-means initialization does not works

### ISSUE THREAD

**Issue by daraha76** [lucidrains/vector-quantize-pytorch#66]
Hi, thanks for sharing your works!

I found some problems when applying K-means clustering initialization in VQ. At the first iteration of VQ right after the initialization, almost all codes are uniformly used. But when it goes into second iteration, only several codes are used very frequently, and most of the codebooks are not used.
I checked the EMA initialization and updating part of the code, and find some issues.

When initializing `self.embed` with K-means clustering,  the `init_embed_` function is called and `self.embed_avg.data` also updated as follows. Here `self.embed_avg` gets same value as `self.embed`.
```
        embed, cluster_size = kmeans(
            data,
            self.codebook_size,
            self.kmeans_iters,
            sample_fn = self.sample_fn,
            all_reduce_fn = self.kmeans_all_reduce_fn
        )

        self.embed.data.copy_(embed)
        self.embed_avg.data.copy_(embed.clone())
```

However, when updating embeddings with EMA, `self.embed_avg` is replaced with the linear interpolation between `self.embed_avg` and `embed_sum`.

```
            embed_sum = einsum('h n d, h n c -> h c d', flatten, embed_onehot)
            self.all_reduce_fn(embed_sum.contiguous())
            ema_inplace(self.embed_avg.data, embed_sum, self.decay)
```

As in the VQ-VAE-2 paper, `embed_sum` is  $\sum_{j} E(x)_{i,j}^{(1)}$.
But `self.embed_avg` after initialization contains $e_i^{0}$, which is much smaller value than $m_i^{0}$. So, performing EMA between 
`self.embed_avg` and  `embed_sum` may lead EMA into value far from the k-means initialization.

So I assume that initializing `self.embed_avg` with $\sum_{j} E(x)_{i,j}^{(0)}$ may be more accurate choice!

**Comment by lucidrains** [comment]
@daraha76 yes you are right, i do think that is problematic 🙏 

could you try [1.6.31](https://github.com/lucidrains/vector-quantize-pytorch/commit/da2fb35abf7d33ed02d0fde1740af7ffa157af9a) and see if that alleviates the issue you are experiencing?

**Comment by daraha76** [comment]
Yep, now it works well. Thank you for your fast updating!
