### ISSUE TITLE
Accessing quantizer codebook

### ISSUE THREAD

**Issue by notmahi** [lucidrains/vector-quantize-pytorch#7]
In [line 278 of `vector_quantize_pytorch.py`](https://github.com/lucidrains/vector-quantize-pytorch/blob/826c620d90deabb1153ccaabd7d9ae50889c33e6/vector_quantize_pytorch/vector_quantize_pytorch.py#L278) shouldn't the property return `self._codebook.embed` and not `self._codebook.codebook`? As I see it, the codebook classes don't even have a `codebook` property.

**Comment by lucidrains** [comment]
@notmahi oh shoot, you are right, should be fixed in 0.3.10!
