### ISSUE TITLE
Examples issue on how to flatten the image-like input.

### ISSUE THREAD

**Issue by Nauw1010** [lucidrains/vector-quantize-pytorch#70]
https://github.com/lucidrains/vector-quantize-pytorch/blob/315098f91b1bbe7537eb7d03fe60f629a36ca8d1/examples/autoencoder.py#L45C18-L45C58
`x_flat = x.view(x.size(0), -1, x.size(1))`

For this line, if I understand correctly, we are trying to flat the images in shape (B, C, W, H) to (B, W*H, C). However, is the .view() operation able to do that? I suppose the rearrange() or permute() methods are more meaningful here, otherwise the last dim would not be the tensor of the pixel value in different channels? 

Please correct me if I am wrong, as I have tried both but not much difference in this case. I am just a bit confused about this. Thank you very much!

**Comment by lucidrains** [comment]
@Nauw1010 ah yes, that does not look right

should be fixed, and takes advantage of an in-built feature for handling image feature maps!

**Comment by Nauw1010** [comment]
Thank you for your response!
