### ISSUE TITLE
Cannot reconstruct Quantized from trained codeblock and indices

### ISSUE THREAD

**Issue by efteli** [lucidrains/vector-quantize-pytorch#71]
What I would like to do is to train the ResidualVQ and later on use the indices only (as well as the trained codeblocks) to reconstruct the quantized data. However, get_codes_from_indices does not seem to be returning the same as quantized. Do you mind clarifying this?

**Comment by lucidrains** [comment]
@efteli would check out the code sample from https://github.com/lucidrains/vector-quantize-pytorch/issues/44

**Comment by efteli** [comment]
Awesome, thanks a lot.
