### ISSUE TITLE
PyTorch Python 3.8 CI failures caused by `list[int]`

### ISSUE THREAD

**Issue by jon-chuang** [lucidrains/vector-quantize-pytorch#76]
Was fixed in latest commit https://github.com/lucidrains/vector-quantize-pytorch/commit/f1f3f3de20c8647979605a5fc5488ae0c627859a
Would you might publishing a new pypi e.g. `1.80b`?

**Comment by lucidrains** [comment]
@jon-chuang hey, that commit doesn't change anything functionally, just mostly personal style

**Comment by lucidrains** [comment]
@jon-chuang ohh got it yea, ugh types

releasing

**Comment by lucidrains** [comment]
@jon-chuang ok should be fixed in 1.8.1
