### ISSUE TITLE
[feature] advice for add 'Additive VQ'

### ISSUE THREAD

**Issue by wl3b10s** [lucidrains/vector-quantize-pytorch#79]
what about include beam search feature for VQ?

like implementation in 
' https://gitlab.com/speech-interaction-technology-aalto-university/vq-variants/-/blob/main/additive_vq.py?ref_type=heads '

**Comment by lucidrains** [comment]
@wl3b10s is there a paper for this?

**Comment by wl3b10s** [comment]
> @wl3b10s is there a paper for this?
please check:

Stochastic Optimization of Vector Quantization Methods in Application to Speech and Image Processing  ICASSP 2023. 
https://acris.aalto.fi/ws/portalfiles/portal/112051687/icassp.pdf

**Comment by lucidrains** [comment]
@wl3b10s probably won't be building this one
