### ISSUE TITLE
indices to codes doesn't work as expected for batched sequences

### ISSUE THREAD

**Issue by theAdamColton** [lucidrains/vector-quantize-pytorch#82]
if indices is (batch, sequence, number of codebooks), then this method returns codes as (batch,z channels,sequence) instead of what I was expecting to be (batch,sequence,z channels) 

https://github.com/lucidrains/vector-quantize-pytorch/blob/f6ebbc15993b798a33dc72696dff8708b4ba900a/vector_quantize_pytorch/lookup_free_quantization.py#L152-L153

I was confused for a minute because my reconstruction from just the indices was really bad, before finding that the dims were being swapped here

**Comment by lucidrains** [comment]
@theAdamColton oops, should be fixed in 1.9.18!

**Comment by lucidrains** [comment]
@theAdamColton have you tried FSQ at all?

**Comment by theAdamColton** [comment]
No
For me LFQ is convenient because I don't have to worry about picking the finite levels

**Comment by lucidrains** [comment]
@theAdamColton ok sounds good, do let me know if you end up trying FSQ

**Comment by lucidrains** [comment]
@theAdamColton but yea, i agree LFQ is the way to go for now
