### ISSUE TITLE
Multi headed VQ get_codes_from_indices doesnt return a correct output

### ISSUE THREAD

**Issue by efteli** [lucidrains/vector-quantize-pytorch#83]
An example is below. I tried to reshape and sum but it doesn't match the original quantization then. 
I would like to figure out how to use indices on a pre-trained vq, so that I can reconstruct by using the given indices.
```
vq = VectorQuantize(
            dim=48,
            codebook_dim=256,
            heads=8,      
            separate_codebook_per_head=True,  
            codebook_size=256,
        )
x = torch.rand([1024, 48])
quantized, indices, commit_loss = vq(x.unsqueeze(1))
quantized = quantized.squeeze(1) # Quantized shape is correct!
re_quantized = vq.get_codes_from_indices(indices)
re_quantized.shape is [1024, 1, 3072]
```

**Comment by efteli** [comment]
It seems like another step is needed:
`
re_quantized = vq.project_out(re_quantized)
`

It would be nicer if we could consolidate these two steps. Since the documentation is not available for such cases, it makes it hard to find the correct approach.

**Comment by lucidrains** [comment]
@efteli yea, i think what i may do is introduce a `get_vq_output_from_indices` function

the thing is, you may want the raw codes from the codebook, before the output projection

**Comment by lucidrains** [comment]
let's just keep this issue open as a reminder

**Comment by lucidrains** [comment]
@efteli you can now use the convenience method [here](https://github.com/lucidrains/vector-quantize-pytorch/commit/905e43833f61bb7421795d33c99f7addacc25d39#diff-8bcd9c958b614ce130dc4091c094d4cfcc2023716823c181e3a9edaddbcd433dR837)

**Comment by efteli** [comment]
Thanks a lot, this is super helpful.
