### ISSUE TITLE
How to use vq loss to update codebook ?

### ISSUE THREAD

**Issue by liutaocode** [lucidrains/vector-quantize-pytorch#84]
Hello, in the article on vq-gan, there are three terms of loss: reconstruction loss, vq loss, and commit loss. I can implement the reconstruction loss by myself, and the commit loss is also mentioned in the interface. But how should I use the vq loss to update the codebook? Should I use the parameter "learnable_codebook" and pass it to the optimizer myself? Thank you very much for your help.

**Comment by lucidrains** [comment]
@liutaocode yes, that's right, you'd use the learnable codebook. an alternative is to use exponential moving average update, which some papers have shown to yield just as good results

however, if you want to be at the cutting edge, i'd suggest looking into the recently proposed [lookup free quantization](https://arxiv.org/abs/2310.05737)

**Comment by liutaocode** [comment]
@lucidrains Thank you very much for your quick response. I will try it out, and I really appreciate it.

**Comment by liutaocode** [comment]
> @liutaocode yes please, do let me know how LFQ fares

Copy
