### ISSUE TITLE
Perhaps wrong formula in finite_scalar_quantization.py

### ISSUE THREAD

**Issue by StarCycle** [lucidrains/vector-quantize-pytorch#86]
https://github.com/lucidrains/vector-quantize-pytorch/blob/d6dcc9e3fed65fcd0567f957f5ea39a3deb9904f/vector_quantize_pytorch/finite_scalar_quantization.py#L82-L87

In the Google code, the offset seems to be 1.0, 0.0, 0.5

https://github.com/google-research/google-research/blob/513d75625c30a9080d8afdcc1ba1bde46c573d62/fsq/fsq.ipynb#L96C1-L101C62

Maybe I don't fully understand how it works...

**Comment by lucidrains** [comment]
@StarCycle it is equivalent

the logic for that line is `if the level is even, then offset is 0.5 vs 0.0` vs `if the level is odd, then offset i 0.0 vs 0.5`
