### ISSUE TITLE
FSQ implementations' bug

### ISSUE THREAD

**Issue by scenarios** [lucidrains/vector-quantize-pytorch#94]
<img width="948" alt="image" src="https://github.com/lucidrains/vector-quantize-pytorch/assets/15104876/074de9af-601e-4767-a9bd-61dfc80cbb1c">

Your implementation on bound function might be incorrect.
tan() is not the inverse of tanh().

**Comment by lucidrains** [comment]
ah yes, i see it

the reason is bc it was transcribed from the pseudocode in the paper

<img width="374" alt="Screen Shot 2023-12-15 at 6 36 48 AM" src="https://github.com/lucidrains/vector-quantize-pytorch/assets/108653/94ae7f27-5b72-4008-b971-b961bbf975dd">

@fab-jul do you have any thoughts?

**Comment by lucidrains** [comment]
https://github.com/lucidrains/vector-quantize-pytorch/pull/95 will merge if author confirms this is an error

**Comment by fab-jul** [comment]
Hi yes this is a mistake, should be [arctanh](https://pytorch.org/docs/stable/generated/torch.arctanh.html).

Note that it barely matters as it's called with a value around 0, where both are similar.

Also note that the whole `bound` function is really ad-hoc and should be revisited. for example, maybe it should be symmetric around 0 also for even numbers. If anyone has some insights let me know.

**Comment by lucidrains** [comment]
@fab-jul yea i figured as i hear from a lot of people having success with FSQ! let me get this merged in just for correctness sake

@scenarios thank you for spotting this
