### ISSUE TITLE
Wrong implementation on residual fsq

### ISSUE THREAD

**Issue by scenarios** [lucidrains/vector-quantize-pytorch#96]
1. scale should be (levels - 1) ** (-ind), which is equivalent to the min interval at current residual level.
2.  the initial residual should be bound(x) rather than x, as the quantized code is bounded one.

**Comment by lucidrains** [comment]
@scenarios would you like to highlight the lines of code you are referring to? a pull request would be best (for a code diff)

we can pull in the author then

**Comment by lucidrains** [comment]
@scenarios would you like to highlight the lines of code you are referring to?

**Comment by lucidrains** [comment]
@scenarios oh crap, this is referring to my makeshift implementation

what you say makes sense.. made the change!
